### ISSUE TITLE
Merging files during markDuplicate

### ISSUE THREAD

**Issue by marchoeppner** [joshua-d-campbell/nf-GATK_Exome_Preprocess#1]
Hi,
this pipeline has been super-helpful in figuring out how to use Nextflow for an exome pipeline. Just a quick question  tho - maybe I am missing something, but this line:

runMarkDuplicatesOutput_grouped_by_sample = runMarkDuplicatesOutput.groupTuple(by: [0])

Uses position 0 as a grouping variable - which based on the output of the upstream stage would be the "IndividualID", not "SampleID" - or am I reading this wrong? Which would be a problem, if the goal is in fact to have the processing being performed on a "per sample" basis from that point onwards. 

Kind regards,
Marc

**Comment by marchoeppner** [comment]
Maybe as a follow-up - what does the merging_by_sample do exactly? During MD, the pipeline seems to group by IndivID and sampleID - so the output should, I assume, is the deduped sample BAM file (since sampleIDs are presumably unique per Individual?).

**Comment by joshua-d-campbell** [comment]
Hi Marc,
The next steps are MarkDuplicate are the GATK TargetCreator and Realignment around indels. These steps work best to clean around germline indels if you give it **_all_** samples from an individual (e.g. tumor and normal pair) as the algorithm can pool information across samples. In the pipeline, the samples are grouped by individual ID (i.e. column 0) and sent to the next process.

Best,
Josh
